# permissions for end users to edit appcrs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: appcr-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: app-resource-demo
    app.kubernetes.io/part-of: app-resource-demo
    app.kubernetes.io/managed-by: kustomize
  name: appcr-editor-role
rules:
- apiGroups:
  - webappres.shi.io
  resources:
  - appcrs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webappres.shi.io
  resources:
  - appcrs/status
  verbs:
  - get
