# permissions for end users to view dbcrs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dbcr-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: app-resource-demo
    app.kubernetes.io/part-of: app-resource-demo
    app.kubernetes.io/managed-by: kustomize
  name: dbcr-viewer-role
rules:
- apiGroups:
  - webappres.shi.io
  resources:
  - dbcrs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webappres.shi.io
  resources:
  - dbcrs/status
  verbs:
  - get
